name: Prepare sources

on:
  workflow_call:


jobs:
  get_sources:
    runs-on: ubuntu-latest

    env:
        beremiz_revisionid: 7509932c74ddc5909ddc61ecb2fad2d0e5749805
        matiec_revisionid: 7949c0bda1787de9c7cacaa4876ede49f85262dd
        canfestival_revisionid: 7cd1f5e5851f527935d88898c5bd9fc5a41e158a
        Modbus_revisionid: 74a5f6a2c3f9b61308a62fc58bbe10572d79a003
        # v1.3.7
        open62541_revisionid: b8ac9e77f703e6ba5c012b886a8821037503daa6


    steps:
    - uses: actions/checkout@v5
      with:
          path: beremiz_public_dist

    # repositories are directly checked out where Makerfile expects them to be
    - uses: actions/checkout@v5
      with:
          repository: beremiz/beremiz
          ref: ${{ env.beremiz_revisionid }}
          path: build/sources/beremiz

    - uses: actions/checkout@v5
      with:
          repository: beremiz/matiec
          ref: ${{ env.matiec_revisionid }}
          path: build/sources/matiec

    - uses: actions/checkout@v5
      with:
          repository: beremiz/canfestival
          ref: ${{ env.canfestival_revisionid }}
          path: build/sources/canfestival

    - uses: actions/checkout@v5
      with:
          repository: beremiz/Modbus
          ref: ${{ env.Modbus_revisionid }}
          path: build/sources/Modbus

    - uses: actions/checkout@v5
      with:
          repository: open62541/open62541
          ref: ${{ env.open62541_revisionid }}
          path: build/sources/open62541

    - name: Keep Makfile satisfied and generate revisions.txt
      run: |
        touch build/sources/beremiz_stamp
        touch build/sources/matiec_stamp
        touch build/sources/canfestival_stamp
        touch build/sources/Modbus_stamp
        touch build/sources/open62541_stamp
        touch build/sources/beremiz_src
        touch build/sources/matiec_src
        touch build/sources/canfestival_src
        touch build/sources/Modbus_src
        touch build/sources/open62541_src
        touch build/own_sources
        cat >> build/revisions.txt <<EOF
        beremiz_public_dist ${{ github.sha }}
        beremiz ${{ env.beremiz_revisionid }}
        matiec ${{ env.matiec_revisionid }}
        canfestival ${{ env.canfestival_revisionid }}
        Modbus ${{ env.Modbus_revisionid }}
        open62541 ${{ env.open62541_revisionid }}
        EOF

    - name: Tar files
      run: tar -cvf sources.tar .

    - name: Upload source artifact
      uses: actions/upload-artifact@v6
      with:
        name: source_package
        path: sources.tar
